///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000-2018 Ericsson Telecom AB
//
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v2.0
// which accompanies this distribution, and is available at
// https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
///////////////////////////////////////////////////////////////////////////////
//  File:         SCCP_EncDec.cc
//  Rev:          R7A
//  Prodnr:       CNL 113 341
//  Updated:      2007-09-17
//  Contact:      http://ttcn.ericsson.se

// Please note: Because the encoder/decoder functions are generated by the 
// TITAN, the SCCP_EncDec.cc is kept only for compatibility issue and 
// should be removed from the projects.
